[package]
name = "test_grs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
grs = { path = "../grs" }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["console"] }

